<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError" kind="class" language="Python" prot="public">
    <compoundname>composite_manager_client::exceptions::ApiKeyError</compoundname>
    <basecompoundref refid="classcomposite__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">composite_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
    <basecompoundref refid="classcomposite__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">composite_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a1a41c3a4c0ea3227c13c4e556aaa5f8b" prot="public" static="no" mutable="no">
        <type></type>
        <definition>composite_manager_client.exceptions.ApiKeyError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" line="96" column="1" bodyfile="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" bodystart="96" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a58c9bb09c7dcb34ce3c6dd54e7f3d4d3" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def composite_manager_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      <memberdef kind="function" id="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a58c9bb09c7dcb34ce3c6dd54e7f3d4d3" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def composite_manager_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/composite_manager_client/composite_manager_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/editable_copies/composite_manager_client/composite_manager_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2007">
        <label>composite_manager_client.exceptions.ApiKeyError</label>
        <link refid="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2008" relation="public-inheritance">
        </childnode>
        <childnode refid="2010" relation="public-inheritance">
        </childnode>
        <childnode refid="2008" relation="public-inheritance">
        </childnode>
        <childnode refid="2010" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2010">
        <label>KeyError</label>
      </node>
      <node id="2009">
        <label>Exception</label>
      </node>
      <node id="2008">
        <label>composite_manager_client.exceptions.OpenApiException</label>
        <link refid="classcomposite__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2009" relation="public-inheritance">
        </childnode>
        <childnode refid="2009" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2011">
        <label>composite_manager_client.exceptions.ApiKeyError</label>
        <link refid="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2012" relation="public-inheritance">
        </childnode>
        <childnode refid="2014" relation="public-inheritance">
        </childnode>
        <childnode refid="2012" relation="public-inheritance">
        </childnode>
        <childnode refid="2014" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2014">
        <label>KeyError</label>
      </node>
      <node id="2013">
        <label>Exception</label>
      </node>
      <node id="2012">
        <label>composite_manager_client.exceptions.OpenApiException</label>
        <link refid="classcomposite__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2013" relation="public-inheritance">
        </childnode>
        <childnode refid="2013" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" line="86" column="1" bodyfile="OpenAPI/tests/composite_manager_client/composite_manager_client/exceptions.py" bodystart="86" bodyend="103"/>
    <listofallmembers>
      <member refid="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a58c9bb09c7dcb34ce3c6dd54e7f3d4d3" prot="public" virt="non-virtual"><scope>composite_manager_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a58c9bb09c7dcb34ce3c6dd54e7f3d4d3" prot="public" virt="non-virtual"><scope>composite_manager_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classcomposite__manager__client_1_1exceptions_1_1ApiKeyError_1a1a41c3a4c0ea3227c13c4e556aaa5f8b" prot="public" virt="non-virtual"><scope>composite_manager_client::exceptions::ApiKeyError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
