<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classdlg_1_1exceptions_1_1InvalidRelationshipException" kind="class" language="Python" prot="public">
    <compoundname>dlg::exceptions::InvalidRelationshipException</compoundname>
    <basecompoundref refid="classdlg_1_1exceptions_1_1DaliugeException" prot="public" virt="non-virtual">dlg.exceptions.DaliugeException</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a934b9d27d392a6a4882af25156687247" prot="public" static="no" mutable="no">
        <type></type>
        <definition>dlg.exceptions.InvalidRelationshipException::rel</definition>
        <argsstring></argsstring>
        <name>rel</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="56" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="56" bodyend="-1"/>
      </memberdef>
      <memberdef kind="variable" id="classdlg_1_1exceptions_1_1InvalidRelationshipException_1af05a9b3ce596435cb330f90673fcf3c6" prot="public" static="no" mutable="no">
        <type></type>
        <definition>dlg.exceptions.InvalidRelationshipException::reason</definition>
        <argsstring></argsstring>
        <name>reason</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="57" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="57" bodyend="-1"/>
      </memberdef>
      <memberdef kind="variable" id="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a7ebb2f8b9cd03f4e5316d7f562e54f73" prot="public" static="no" mutable="no">
        <type></type>
        <definition>dlg.exceptions.InvalidRelationshipException::msg</definition>
        <argsstring></argsstring>
        <name>msg</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="58" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="58" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classdlg_1_1exceptions_1_1InvalidRelationshipException_1ad5db2a3f3443096d75833ab591efaaa3" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def dlg.exceptions.InvalidRelationshipException.__init__</definition>
        <argsstring>(self, rel, reason)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>rel</type>
          <defname>rel</defname>
        </param>
        <param>
          <type>reason</type>
          <defname>reason</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="54" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="54" bodyend="59"/>
      </memberdef>
      <memberdef kind="function" id="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a6821b07518bc941956f5c5a38f073889" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def dlg.exceptions.InvalidRelationshipException.__str__</definition>
        <argsstring>(self, args, kwargs)</argsstring>
        <name>__str__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>args</type>
          <defname>args</defname>
        </param>
        <param>
          <type>kwargs</type>
          <defname>kwargs</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="60" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="60" bodyend="62"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>An exception thrown when a relationship between two Drops has been
instructed but is invalid in nature.
</verbatim> </para>    </detaileddescription>
    <inheritancegraph>
      <node id="2321">
        <label>Exception</label>
      </node>
      <node id="2320">
        <label>dlg.exceptions.DaliugeException</label>
        <link refid="classdlg_1_1exceptions_1_1DaliugeException"/>
        <childnode refid="2321" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2319">
        <label>dlg.exceptions.InvalidRelationshipException</label>
        <link refid="classdlg_1_1exceptions_1_1InvalidRelationshipException"/>
        <childnode refid="2320" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2324">
        <label>Exception</label>
      </node>
      <node id="2323">
        <label>dlg.exceptions.DaliugeException</label>
        <link refid="classdlg_1_1exceptions_1_1DaliugeException"/>
        <childnode refid="2324" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2322">
        <label>dlg.exceptions.InvalidRelationshipException</label>
        <link refid="classdlg_1_1exceptions_1_1InvalidRelationshipException"/>
        <childnode refid="2323" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="daliuge-common/dlg/exceptions.py" line="49" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="49" bodyend="63"/>
    <listofallmembers>
      <member refid="classdlg_1_1exceptions_1_1InvalidRelationshipException_1ad5db2a3f3443096d75833ab591efaaa3" prot="public" virt="non-virtual"><scope>dlg::exceptions::InvalidRelationshipException</scope><name>__init__</name></member>
      <member refid="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a6821b07518bc941956f5c5a38f073889" prot="public" virt="non-virtual"><scope>dlg::exceptions::InvalidRelationshipException</scope><name>__str__</name></member>
      <member refid="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a7ebb2f8b9cd03f4e5316d7f562e54f73" prot="public" virt="non-virtual"><scope>dlg::exceptions::InvalidRelationshipException</scope><name>msg</name></member>
      <member refid="classdlg_1_1exceptions_1_1InvalidRelationshipException_1af05a9b3ce596435cb330f90673fcf3c6" prot="public" virt="non-virtual"><scope>dlg::exceptions::InvalidRelationshipException</scope><name>reason</name></member>
      <member refid="classdlg_1_1exceptions_1_1InvalidRelationshipException_1a934b9d27d392a6a4882af25156687247" prot="public" virt="non-virtual"><scope>dlg::exceptions::InvalidRelationshipException</scope><name>rel</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
