<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classnode__manager__client_1_1exceptions_1_1ApiKeyError" kind="class" language="Python" prot="public">
    <compoundname>node_manager_client::exceptions::ApiKeyError</compoundname>
    <basecompoundref refid="classnode__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">node_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
    <basecompoundref refid="classnode__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">node_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a89e007ef4e2dd7e8c6e6341e44f1856a" prot="public" static="no" mutable="no">
        <type></type>
        <definition>node_manager_client.exceptions.ApiKeyError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="96" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="96" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a010a9e8f80f7a200d4793ec53251a6fa" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def node_manager_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      <memberdef kind="function" id="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a010a9e8f80f7a200d4793ec53251a6fa" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def node_manager_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/node_manager_client/node_manager_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/node_manager_client/node_manager_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2016">
        <label>node_manager_client.exceptions.OpenApiException</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2017" relation="public-inheritance">
        </childnode>
        <childnode refid="2017" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2018">
        <label>KeyError</label>
      </node>
      <node id="2017">
        <label>Exception</label>
      </node>
      <node id="2015">
        <label>node_manager_client.exceptions.ApiKeyError</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2016" relation="public-inheritance">
        </childnode>
        <childnode refid="2018" relation="public-inheritance">
        </childnode>
        <childnode refid="2016" relation="public-inheritance">
        </childnode>
        <childnode refid="2018" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2020">
        <label>node_manager_client.exceptions.OpenApiException</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2021" relation="public-inheritance">
        </childnode>
        <childnode refid="2021" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2022">
        <label>KeyError</label>
      </node>
      <node id="2021">
        <label>Exception</label>
      </node>
      <node id="2019">
        <label>node_manager_client.exceptions.ApiKeyError</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2020" relation="public-inheritance">
        </childnode>
        <childnode refid="2022" relation="public-inheritance">
        </childnode>
        <childnode refid="2020" relation="public-inheritance">
        </childnode>
        <childnode refid="2022" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="86" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="86" bodyend="103"/>
    <listofallmembers>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a010a9e8f80f7a200d4793ec53251a6fa" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a010a9e8f80f7a200d4793ec53251a6fa" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiKeyError_1a89e007ef4e2dd7e8c6e6341e44f1856a" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiKeyError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
