<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classnode__manager__client_1_1exceptions_1_1ApiValueError" kind="class" language="Python" prot="public">
    <compoundname>node_manager_client::exceptions::ApiValueError</compoundname>
    <basecompoundref refid="classnode__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">node_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">ValueError</basecompoundref>
    <basecompoundref refid="classnode__manager__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">node_manager_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">ValueError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classnode__manager__client_1_1exceptions_1_1ApiValueError_1a9d96b3c4a46926fbfc4f3b7ecc13a184" prot="public" static="no" mutable="no">
        <type></type>
        <definition>node_manager_client.exceptions.ApiValueError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="60" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="60" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classnode__manager__client_1_1exceptions_1_1ApiValueError_1aafa168ec039cfbc5762675d2627def76" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def node_manager_client.exceptions.ApiValueError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (list) the path to the exception in the
received_data dict. None if unset
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="50" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="50" bodyend="66"/>
      </memberdef>
      <memberdef kind="function" id="classnode__manager__client_1_1exceptions_1_1ApiValueError_1aafa168ec039cfbc5762675d2627def76" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def node_manager_client.exceptions.ApiValueError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (list) the path to the exception in the
received_data dict. None if unset
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/node_manager_client/node_manager_client/exceptions.py" line="50" column="1" bodyfile="OpenAPI/tests/node_manager_client/node_manager_client/exceptions.py" bodystart="50" bodyend="66"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2064">
        <label>node_manager_client.exceptions.OpenApiException</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2065" relation="public-inheritance">
        </childnode>
        <childnode refid="2065" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2063">
        <label>node_manager_client.exceptions.ApiValueError</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1ApiValueError"/>
        <childnode refid="2064" relation="public-inheritance">
        </childnode>
        <childnode refid="2066" relation="public-inheritance">
        </childnode>
        <childnode refid="2064" relation="public-inheritance">
        </childnode>
        <childnode refid="2066" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2066">
        <label>ValueError</label>
      </node>
      <node id="2065">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2068">
        <label>node_manager_client.exceptions.OpenApiException</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2069" relation="public-inheritance">
        </childnode>
        <childnode refid="2069" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2067">
        <label>node_manager_client.exceptions.ApiValueError</label>
        <link refid="classnode__manager__client_1_1exceptions_1_1ApiValueError"/>
        <childnode refid="2068" relation="public-inheritance">
        </childnode>
        <childnode refid="2070" relation="public-inheritance">
        </childnode>
        <childnode refid="2068" relation="public-inheritance">
        </childnode>
        <childnode refid="2070" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2070">
        <label>ValueError</label>
      </node>
      <node id="2069">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" line="49" column="1" bodyfile="OpenAPI/tests/editable_copies/node_manager_client/node_manager_client/exceptions.py" bodystart="49" bodyend="67"/>
    <listofallmembers>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiValueError_1aafa168ec039cfbc5762675d2627def76" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiValueError</scope><name>__init__</name></member>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiValueError_1aafa168ec039cfbc5762675d2627def76" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiValueError</scope><name>__init__</name></member>
      <member refid="classnode__manager__client_1_1exceptions_1_1ApiValueError_1a9d96b3c4a46926fbfc4f3b7ecc13a184" prot="public" virt="non-virtual"><scope>node_manager_client::exceptions::ApiValueError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
