<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classtranslator__client_1_1exceptions_1_1ApiKeyError" kind="class" language="Python" prot="public">
    <compoundname>translator_client::exceptions::ApiKeyError</compoundname>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">KeyError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classtranslator__client_1_1exceptions_1_1ApiKeyError_1ae41e7e38c71b902e1e2e6279029fa2d8" prot="public" static="no" mutable="no">
        <type></type>
        <definition>translator_client.exceptions.ApiKeyError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="96" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="96" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiKeyError_1a071eb862b7a0176974456c962a78c0a6" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiKeyError_1a071eb862b7a0176974456c962a78c0a6" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiKeyError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/translator_client/translator_client/exceptions.py" line="87" column="1" bodyfile="OpenAPI/tests/translator_client/translator_client/exceptions.py" bodystart="87" bodyend="102"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2024">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2025" relation="public-inheritance">
        </childnode>
        <childnode refid="2025" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2026">
        <label>KeyError</label>
      </node>
      <node id="2025">
        <label>Exception</label>
      </node>
      <node id="2023">
        <label>translator_client.exceptions.ApiKeyError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2024" relation="public-inheritance">
        </childnode>
        <childnode refid="2026" relation="public-inheritance">
        </childnode>
        <childnode refid="2024" relation="public-inheritance">
        </childnode>
        <childnode refid="2026" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2028">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2029" relation="public-inheritance">
        </childnode>
        <childnode refid="2029" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2030">
        <label>KeyError</label>
      </node>
      <node id="2029">
        <label>Exception</label>
      </node>
      <node id="2027">
        <label>translator_client.exceptions.ApiKeyError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiKeyError"/>
        <childnode refid="2028" relation="public-inheritance">
        </childnode>
        <childnode refid="2030" relation="public-inheritance">
        </childnode>
        <childnode refid="2028" relation="public-inheritance">
        </childnode>
        <childnode refid="2030" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="86" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="86" bodyend="103"/>
    <listofallmembers>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiKeyError_1a071eb862b7a0176974456c962a78c0a6" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiKeyError_1a071eb862b7a0176974456c962a78c0a6" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiKeyError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiKeyError_1ae41e7e38c71b902e1e2e6279029fa2d8" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiKeyError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
